In [18]:
import numpy as np
import numpy.random as rand
from numpy.linalg import inv
from Gen_given_sparsity import specific_sparsity_theta
from Gen_tridiagonal import tridiagonal_theta

In [19]:
def mid_element_5MC(sig):
    for i in range(5):
        found = 1
        for j in range(5):
            if j==i:
                continue
            new = 1
            count = 0
            for k in range(5):
                if k != i and k!=j:
                    if new == 1:
                        ratio = sig[i, k]/sig[j, k]
                        new = 0
#                         print ratio
                    if new == 0:
                        if abs(sig[i, k]/sig[j, k] - ratio)<1e-4:
                            count = count + 1
#                             print count, i, "count i"
                if count == 3:
                    found = 0
        if found == 1 :
            return i

In [20]:
def check_4node_star_structure(cov):
    for i in range(4):
        for j in range(4):
            if j==i:
                continue
            new = 1
            for k in range(4):
                if k!=i and k!=j:
                    if new == 1:
                        ratio = cov[k,i]/cov[k,j]
                        new = 0
                    else:
                        if abs(ratio - cov[k,i]/cov[k,j])> 1e-4:
                            return False
    return True
                        

In [21]:
def check_4node_MC_structure(cov):
    count = 0
    pair = []
    for i in range(4):
#         if i in exhausted_nodes:
#             continue
        for j in range(4):
            if j==i: #or j in exhausted_nodes:
                continue
            new = 1
            for k in range(4):
                if k!=i and k!=j:
                    if new == 1:
                        ratio = cov[k,i]/cov[k,j]
                        new = 0
                    else:
                        if abs(ratio - cov[k,i]/cov[k,j])< 1e-6:
                            count = count + 1
                            
                            if count == 1:
                                pair.append(i)
                                pair.append(j)
#                             print count
#                             exhausted_nodes.append([i,j])
#     if len(exhausted_nodes) == 4:
#         return True
#     else:
#         return False
    if count == 4:
        return True, pair
    else:
        return False, []
                            

In [22]:
def check_5node_MC_structure(cov):
    index = [0,1,2,3,4]
#     index1 = [0,1,2,3,4]
    for i in range(5):
        index.remove(i)
        sub_cov = cov[np.ix_(index, index)]
        status, pair = check_4node_MC_structure(sub_cov)
        if status == False:
            return False
        else:
            index.append(i)
    return True


In [23]:
def check_5node_MC_structure1(cov):
    count = 0
    pair = []
    for i in range(5):
#         if i in exhausted_nodes:
#             continue
        for j in range(5):
            if j==i: #or j in exhausted_nodes:
                continue
            new = 1
            for k in range(5):
                if k!=i and k!=j:
                    if new == 1:
                        ratio = cov[k,i]/cov[k,j]
                        new = 0
                    else:
                        if abs(ratio - cov[k,i]/cov[k,j])< 1e-8:
                            count = count + 1
#                             if count == 1:
#                                 pair.append(i)
#                                 pair.append(j)
#                             print count
#                             exhausted_nodes.append([i,j])
#     if len(exhausted_nodes) == 4:
#         return True
#     else:
#         return False
    print count
    if count == 12:
        return True#, pair
    else:
        return False#, []
                            

In [24]:
"""
def switching_nodes(sig, group1, group2, index):
    sub_sig = sig[np.ix_(index, index)]
    status, pair = check_4node_MC_structure(sig)
    if status == False:
        return False, None
    pair2 = [0,1,2,3]
    pair2.remove(pair[0])
    pair2.remove(pair[1])
    for j in range(4):
        if (index[j] not in group1) and (index[j] not in group1):
            break
    new = index[j]
    if j in pair:
        if 
        if index[pair2[0]]
        """

'\ndef switching_nodes(sig, group1, group2, index):\n    sub_sig = sig[np.ix_(index, index)]\n    status, pair = check_4node_MC_structure(sig)\n    if status == False:\n        return False, None\n    pair2 = [0,1,2,3]\n    pair2.remove(pair[0])\n    pair2.remove(pair[1])\n    for j in range(4):\n        if (index[j] not in group1) and (index[j] not in group1):\n            break\n    new = index[j]\n    if j in pair:\n        if \n        if index[pair2[0]]\n        '

In [25]:
n = 10
print range(n-1, n-5, -1)

[9, 8, 7, 6]


In [26]:
def split(sig):
    n = sig.shape[0]
    if n==4:
        status, pair = check_4node_MC_structure(sig)
        if status == False:
#             group1 = pair
#             group2 = [0,1,2,3]
#             group2.remove(group1[0])
#             group2.remove(group1[1])
            group1 = [0,1,2]
            group2 = [3]
#             perm = range(4)
            return group1, group2, group1[1], group2[0]
    start = 1
    group1 = []
    group2 = []
    index = range(4)
    perm = range(n)
    sig_copy = np.zeros((n,n))
    sig_copy[:,:] = sig[:,:]
    orig_pair1 = []
    orig_pair2 = []
#     sub_sig = sig[np.ix_(index, index)]
    while start == 1:
#         print "check"
        sub_sig = sig[np.ix_(index, index)]
        status, pair = check_4node_MC_structure(sub_sig)
        if status == True:
            start = 0
            for j in range(4):
                if j in pair:
                    group1.append(index[j])
                    orig_pair1.append(j)
#                     if j==0 :
#                         minority = 1
                else:
                    group2.append(index[j])
                    orig_pair2.append(j)
#                     if j==0 :
#                         minority = 2
            
#         sub_sig = sig[np.ix_(index, index)]
#         if check_4node_star_structure(sub_sig) == False:
            
        else:
            sig[:,:] = sig_copy[:,:]
            perm = rand.permutation(n)
#             print "test", perm
            sig = sig[np.ix_(perm, perm)]
#     print perm
#     print sig
#     print group1, group2
    majority = 1
    new = orig_pair2[0]
    index1 = [0]*4;
    index2 = [0]*4;
    index1[:] = index[:]
    index2[:] = index[:]
    not_conn1 = index[orig_pair1[0]]
    conn1 = index[orig_pair1[1]]
    not_conn2 = index[orig_pair2[0]]
    conn2 = index[orig_pair2[1]]
#     used = []
    for i in range(n-4):
#         print i, group1, group2, conn1, conn2, index, "i, group1, group2, conn1, conn2, index"
#         if i+4 in group1 or i+4 in group2:
#             continue
        index[new] = i+4
        
        index1[:] = index[:]
        index2[:] = index[:]
#         print index
        sub_sig = sig[np.ix_(index, index)]
        status, pair = check_4node_MC_structure(sub_sig)
        
        if status == True:
#             print index, pair, new, status, "index pair, new, status"
            pair2 = [0,1,2,3]
            pair2.remove(pair[0])
            pair2.remove(pair[1])
            if new in pair:
#                 print "new in group2 MC structure  1"
                pair.remove(new)
                if index[pair[0]] in group1:
#                     print "new in group1 MC structure  1"
                    if index[new] not in group1:
                        group1.append(index[new])
                    
#                     if minority == 2:
                    if index[pair2[0]] in group1:
                        conn1 = index[pair2[0]] 
                    else:
                        conn1 = index[pair2[1]] 
                    if index[orig_pair1[1]] != conn1:
                        index[orig_pair1[0]] = index[orig_pair1[1]]
                        index[orig_pair1[1]] = conn1
                else:
#                     print "new in group2 MC structure  2"
                    if index[new] not in group2:
                        group2.append(index[new])
                    sub_status = False
                    k = 0
                    while(sub_status == False and k<n):
                        if k == conn2 or k in index or k in group1:
                            k = k+1
                            continue
                        check = 0
                        if k > index[new]:
                            index2[new] = k
                            sub_sig2 = sig[np.ix_(index2, index2)]
                            sub_status2, sub_pair2 = check_4node_MC_structure(sub_sig2)
                            if sub_status2 == True:
#                                 print index, pair, new, status, "index pair, new, status"
                                sub_pair22 = [0,1,2,3]
                                sub_pair22.remove(sub_pair2[0])
                                sub_pair22.remove(sub_pair2[1])
                                if new in sub_pair2:
                    #                 print "new in group2 MC structure  1"
                                    sub_pair2.remove(new)
                                    if index[sub_pair2[0]] in group1:
#                                         print "new in group1 MC structure  1"
                                        if k not in group1:
                                            group1.append(k)
                                        check = 1
                                    else:
                                        if k not in group2:
                                            group2.append(k)
                                else:
                                    sub_pair22.remove(new)
                                    if index[sub_pair22[0]] in group1:
#                                         print "new in group1 MC structure  1"
                                        if k not in group1:
                                            group1.append(k)
                                        check = 1
                                    else:
                                        if k not in group2:
                                            group2.append(k)
                            else:
                                if k not in group1:
                                    group1.append(k)
                                check = 1
                                
                        if check == 1:
                            k = k+1
                            continue                           
                        index1[orig_pair1[0]] = k
                        sub_sig1 = sig[np.ix_(index1, index1)]

                        sub_status, sub_pair = check_4node_MC_structure(sub_sig1)
                        if sub_status == True:
                            if k not in group2:
                                group2.append(k)
#                             print "section 2 group 2 MC case"
                            sub_pair2 = [0,1,2,3]
                            sub_pair2.remove(sub_pair[0])
                            sub_pair2.remove(sub_pair[1])
                            if conn1 in sub_pair:
                                sub_pair.remove(conn1)
                                conn2 = index1[sub_pair[0]]
                            else:
                                sub_pair2.remove(conn1)
                                conn2 = index1[sub_pair2[0]]
                            if index[orig_pair2[1]] != conn2:
                                index[orig_pair2[0]] = index[orig_pair2[1]]
                                index[orig_pair2[1]] = conn2
#                         else:
#                             print "section 2 group 2 star case"
                        k = k+1
#                         if len(group2 >= 4):
#                             for j in range(4):
#                                 if j == orig_pair1[1] or index[j] == conn2:
#                                     continue
                                
#                                 k = index1[j]
#                                 index1[j] = group2[1]
#                                 sub_sig1 = sig[np.ix_(index1, index1)]
#                                 sub_status, sub_pair = check_4node_MC_structure(sub_sig1)
#                                 sub_pair2 = [0,1,2,3]
#                                 sub_pair2.remove(sub_pair[0])
#                                 sub_pair2.remove(sub_pair[1])
#                                 if orig_pair1[1] in sub_pair:
#                                     sub_pair.remove(orig_pair1[1])
#                                     conn2 = index[sub_pair[0]]
#                                 else:
#                                     sub_pair2.remove(orig_pair1[1])
#                                     conn2 = index[sub_pair2[0]]

            

            else:                
                pair2.remove(new)
                if index[pair2[0]] in group1:
#                     print "new in group1 MC structure  3"
                    if index[new] not in group1:
                        group1.append(index[new])
                    
#                     if minority == 2:
                    if index[pair[0]] in group1:
                        conn1 = index[pair[0]] 
                    else:
                        conn1 = index[pair[1]]
                    if index[orig_pair1[1]] != conn1:
                        index[orig_pair1[0]] = index[orig_pair1[1]]
                        index[orig_pair1[1]] = conn1
                else:
#                     print "new in group2 MC structure  4"
                    if index[new] not in group2:
                        group2.append(index[new])
                    sub_status = False
                    k = 0
                    while(sub_status == False and k<n):
                        if k == conn2 or k in index or k in group1:
                            k = k+1
                            continue
                        check = 0
                        if k > index[new]:
                            index2[new] = k
#                             print index2
                            sub_sig2 = sig[np.ix_(index2, index2)]
                            sub_status2, sub_pair2 = check_4node_MC_structure(sub_sig2)
#                             print sub_status2, index2, "sub_status2, index2"
                            if sub_status2 == True:
#                                 print index, pair, new, status, "index pair, new, status"
                                sub_pair22 = [0,1,2,3]
                                sub_pair22.remove(sub_pair2[0])
                                sub_pair22.remove(sub_pair2[1])
                                if new in sub_pair2:
                    #                 print "new in group2 MC structure  1"
                                    sub_pair2.remove(new)
                                    if index[sub_pair2[0]] in group1:
#                                         print "new in group1 MC structure  1"
                                        if k not in group1:
                                            group1.append(k)
                                        check = 1
                                    else:
                                        if k not in group2:
                                            group2.append(k)
                                else:
                                    sub_pair22.remove(new)
                                    if index[sub_pair22[0]] in group1:
#                                         print "new in group1 MC structure  1"
                                        if k not in group1:
                                            group1.append(k)
                                        check = 1
                                    else:
                                        if k not in group2:
                                            group2.append(k)
                            else:
                                if k not in group1:
                                    group1.append(k)
                                check = 1
                                
                        if check == 1:
                            k = k+1
                            continue
                            
                            
                        index1[orig_pair1[0]] = k
#                         print index1, "index1"
                        sub_sig1 = sig[np.ix_(index1, index1)]
                        sub_status, sub_pair = check_4node_MC_structure(sub_sig1)
                        if sub_status == True:
#                             print "group 2 section 4 MC case"
                            sub_pair2 = [0,1,2,3]
                            sub_pair2.remove(sub_pair[0])
                            sub_pair2.remove(sub_pair[1])
#                             print sub_pair, sub_pair2, orig_pair1[1], "sub_pair, sub_pair2, orig_pair1[1]"
                            if orig_pair1[1] in sub_pair:

                                sub_pair.remove(orig_pair1[1])
                                conn2 = index1[sub_pair[0]]
#                                 print conn2, "sub_pair, conn2"
                            else:
                                sub_pair2.remove(orig_pair1[1])
                                conn2 = index1[sub_pair2[0]]
#                                 print conn2, "sub_pair2, conn2"
                            if index[orig_pair2[1]] != conn2:
                                index[orig_pair2[0]] = index[orig_pair2[1]]
                                index[orig_pair2[1]] = conn2
                            
                            
#                         else:
#                             print "group 2 section 4 star case"
                        k = k+1
        else:
#             print "group 1 star"
#             print index, pair, new, status, "index pair, new, status"
#             print "check arrival", index, minority
            if index[new] not in group1:
                group1.append(index[new])
#             print index[new]
#             group2.append(index[new])
            sub_status2 = False
            k = 0
            check = 0
            while((sub_status2 == False and k<n) or (check == 1 and k<n)):
                if k == conn1 or k == index[new] or k in group2 or k in index2:
                    k = k+1
                    continue
                check = 0
#                 if k > index[new]:
                index2[orig_pair1[0]] = k
#                             print index2
                sub_sig2 = sig[np.ix_(index2, index2)]
                sub_status2, sub_pair2 = check_4node_MC_structure(sub_sig2)
#                 print sub_status2, index2, "sub_status2, index2"
                if sub_status2 == True:
#                                 print index, pair, new, status, "index pair, new, status"
                    sub_pair22 = [0,1,2,3]
                    sub_pair22.remove(sub_pair2[0])
                    sub_pair22.remove(sub_pair2[1])
                    if orig_pair1[0] in sub_pair2:
        #                 print "new in group2 MC structure  1"
                        sub_pair2.remove(orig_pair1[0])
                        if index[sub_pair2[0]] in group1:
#                             print "new in group1 MC structure  5"
                            if k not in group1:
                                group1.append(k)
                                if index[sub_pair22[0]] in group2:
                                    conn1 = index[sub_pair22[1]]
                                else:
                                    conn1 = index[sub_pair22[0]]
                                index[orig_pair1[1]] = conn1
                                break
                        else:
                            if k not in group2:
                                group2.append(k)
                            check = 1
                    else:
                        sub_pair22.remove(orig_pair1[0])
                        if index[sub_pair22[0]] in group1:
#                             print "new in group1 MC structure  5"
                            if k not in group1:
                                group1.append(k)
                                if index[sub_pair2[0]] in group2:
                                    conn1 = index[sub_pair2[1]]
                                else:
                                    conn1 = index[sub_pair2[0]]
                                if index[orig_pair1[1]] != conn1:
                                    index[orig_pair1[0]] = index[orig_pair1[1]]
                                    index[orig_pair1[1]] = conn1
                                break
                        else:
                            if k not in group2:
                                group2.append(k)
                            check = 1
                else:
                    if k not in group1:
                        group1.append(k)
                k = k+1

#                     if check == 1:
#                         k = k+1
#                         continue


#                 index1[orig_pair1[0]] = k
#                 print index1, "index1"
#                 sub_sig1 = sig[np.ix_(index1, index1)]
#                 sub_status, sub_pair = check_4node_MC_structure(sub_sig1)
#                 if sub_status == True:
#                     print "group 2 section 4 MC case"
#                     sub_pair2 = [0,1,2,3]
#                     sub_pair2.remove(sub_pair[0])
#                     sub_pair2.remove(sub_pair[1])
#                     print sub_pair, sub_pair2, orig_pair1[1], "sub_pair, sub_pair2, orig_pair1[1]"
#                     if orig_pair1[1] in sub_pair:

#                         sub_pair.remove(orig_pair1[1])
#                         conn2 = index1[sub_pair[0]]
#                         print conn2, "sub_pair, conn2"
#                     else:
#                         sub_pair2.remove(orig_pair1[1])
#                         conn2 = index1[sub_pair2[0]]
#                         print conn2, "sub_pair2, conn2"
#                     index[orig_pair2[1]] = conn2
#                 else:
#                     print "group 2 section 4 star case"
#                 k = k+1

#             if len(group1) >= 4:
#                 for j in range(4):
#                     if j == orig_pair2[1] or index1[j] == conn1:
#                         continue
#                     k = index1[j]
#                     index1[j] = group1[2]
#                     sub_sig1 = sig[np.ix_(index1, index1)]
#                     sub_status, sub_pair = check_4node_MC_structure(sub_sig1)
#                     index1[j] = k
#                     sub_pair2 = [0,1,2,3]
#                     sub_pair2.remove(sub_pair[0])
#                     sub_pair2.remove(sub_pair[1])
#                     if orig_pair2[1] in sub_pair:
#                         sub_pair.remove(orig_pair2[1])
#                         conn1 = index[sub_pair[0]]
#                     else:
#                         sub_pair2.remove(orig_pair2[1])
#                         conn1 = index[sub_pair2[0]]
#             if majority == 1:
#                 group2.append(index[new])
# #                 minority = 2
#             else :
                
#                 minority = 1
                    
#                 if index[pair[0]] in group1 or index[pair[1]] in group1:
#                     group1.append(index[i%4])
#                 else:
#                     group2.append(index[i%4])
        
    n1 = len(group1)
    n2 = len(group2)
    perm = np.array(perm) 
    group1 = perm[np.ix_(group1)]
    group2 = perm[np.ix_(group2)]
    group1 = list(group1)
    group2 = list(group2)
#     print perm, "perm"
#     print conn1, conn2, "conn1, conn2"
    conn1 = perm[conn1]
    conn2 = perm[conn2]
                
#         index[i%4] = i+4
    return group1, group2, conn1, conn2#, perm

In [27]:
def check_leaf(sig, group1, group2, conn1, conn2):
    index = [-1,-1,-1,-1,-1]
#     print index, group1, group2
    index[0] = group2[0]
    index[1] = group2[1]
    index[2] = conn1
    check_leaf1 = 1
    check_leaf2 = 1
    
    if group1[0] == conn1:
        index[3] = group1[1]
    else:
        index[3] = group1[0]
    for i in group1:     
        if i in index:
            continue
#         print index
        index[4] = i
#         print index
        sub_sig = sig[np.ix_(index, index)]
        if check_5node_MC_structure(sub_sig) == True:
            mid = mid_element_5MC(sub_sig)
            if mid != 2:
                check_leaf1 = 0
#                 print index, "1, MC"
                break
        else:
            check_leaf1 = 0
#             print index, "1, non MC"
            break
    index = [-1,-1,-1,-1,-1]
    index[0:2] = group1[0:2]
    index[2] = conn2
    if group2[0] == conn2:
        index[3] = group2[1]
    else:
        index[3] = group2[0]
    for i in group2:
        if i in index:
            continue
        index[4] = i
#         print index
        sub_sig = sig[np.ix_(index, index)]
        if check_5node_MC_structure(sub_sig) == True:
            mid = mid_element_5MC(sub_sig)
            if mid != 2:
                check_leaf2 = 0
#                 print index, "2, MC"
                break
        else:
            check_leaf2 = 0
#             print index, "2, non MC"
            break
    return check_leaf1, check_leaf2

In [28]:
def check_leaf_prec(prec, node):
    n = prec.shape[0]
    count = 0
    for i in range(n):
        if prec[i, node] !=0:
            count = count +1
        if count > 2:
            return False
    return True

In [29]:
def exchange_leaf_internal(prec, node):
    n = prec.shape[0]
    for i in range(n):
        if prec[i, node] !=0:
            if check_leaf_prec(prec, i):
                break
    res_row = prec[i, :]
    res_col = prec[:, i]
    prec[i, :] = prec[node, :]
    prec[:, i] = prec[:, node]
    prec[node, :] = res_row
    prec[:, node] = res_col
    return prec
            

In [30]:
def candidate_connections(sig, part1, part2, conn1, conn2):
#     print part1, part2, conn1, conn2, "part1, part2, conn1, conn2"
    n1 = len(part1)
    n2 = len(part2)
    cand_conns1 = range(n1)
    cand_conns1[:] = part1[:] 
    cand_conns2 = range(n2)
    cand_conns2[:] = part2[:] 
    if n1 == 1:
        cand_conns2.remove(conn2)
        cand_conns1.remove(conn1)
        return cand_conns1, cand_conns2
    if n2 == 1:
        cand_conns2.remove(conn2)
        cand_conns1.remove(conn1)
        return cand_conns1, cand_conns2
    if n1==2:
        cand_conns1.remove(conn1)
    else:
        index = [conn1, part2[0], part2[1], 0, 0]
        for i in cand_conns1:
            del_i = False
            if i == conn1:
                continue
            for j in cand_conns1:
                if j== conn1 or j==i:
                    continue
                index[3] = i
                index[4] = j
                sub_sig = sig[np.ix_(index, index)]
                MC_5node = check_5node_MC_structure(sub_sig)
#                 print index, MC_5node, "index, MC5node"
                if MC_5node == True:
                    del_i = True
                    cand_conns1.remove(j)
#                 print cand_conns1
            if del_i == True:
#                 print i, "i"
                cand_conns1.remove(i)
#             print cand_conns1
        cand_conns1.remove(conn1)
#         print cand_conns1
                
    if n2==2:
        cand_conns2.remove(conn2)
    
    else:
        index = [conn2, part1[0], part1[1], 0, 0]
        for i in cand_conns2:
            del_i = False
            if i == conn2:
                continue
            for j in cand_conns2:
                if j== conn2 or j==i:
                    continue
                index[3] = i
                index[4] = j
                sub_sig = sig[np.ix_(index, index)]
                MC_5node = check_5node_MC_structure(sub_sig)
                if MC_5node == True:
                    del_i = True
                    cand_conns2.remove(j)
            if del_i == True:
                cand_conns2.remove(i)          
        cand_conns2.remove(conn2)
    return cand_conns1, cand_conns2
                

In [31]:
def check_candidates1(sig, connections, cand_conns, conn, group):
    index = [-1,-1,-1,-1,-1]
#     print connections, cand_conns, conn, group, "connections, cand_conns, conn, group"
#     group.remove(conn)
    for i in cand_conns:
        index[0] = conn
        index[1] = i
        count = 0
        for j in group:
            if j!=i:
                index[count+3] = j
                count = count + 1
            if count == 2:
                break   
#         print index
        for j in connections:
            if j in index:
                continue
            index[2] = j
            sub_sig = sig[np.ix_(index, index)]
#             print index, check_5node_MC_structure(sub_sig), "index, check_5node_MC_structure(sub_sig)"
            if check_5node_MC_structure(sub_sig) == False:
                continue
            mid = mid_element_5MC(sub_sig)
#             print mid, "mid:"
            
            if mid == 1:
                conn = i
                
        
    return conn
                
            

In [32]:
def check_candidates(sig, connections, cand_conns, conn, group):
    index = [-1,-1,-1,-1]
#     print connections, cand_conns, conn, group, "connections, cand_conns, conn, group"
#     group.remove(conn)
    for i in cand_conns:
        index[0] = conn
        index[1] = i
        count = 0
        index[2] = group[0]
#         print index
        for j in connections:
            if j in index:
                continue
            index[3] = j
#             print index
            sub_sig = sig[np.ix_(index, index)]
#             print index, check_5node_MC_structure(sub_sig), "index, check_5node_MC_structure(sub_sig)"
            status, pair1 = check_4node_MC_structure(sub_sig)
            
            if status == False:
                continue
            pair2 = [0,1,2,3]
            pair2.remove(pair1[0])
            pair2.remove(pair1[1])
            pair1_index = [index[i] for i in pair1]
            pair2_index = [index[i] for i in pair2]
            
            if group[0] in pair1_index:
                pair1_index.remove(group[0])
                if pair1_index[0] in cand_conns:
                    conn = pair1_index[0]
            else:
                pair2_index.remove(group[0])
                if pair2_index[0] in cand_conns:
                    conn = pair2_index[0]
            break

#             else
#             print mid, "mid:"
            
#             if mid == 1:
#                 conn = i
                
        
    return conn

In [33]:
first_access = 1
append1 = 0
append2 = 0
connections = []

def learn_tree(sig, index, center_3node = None):
    global first_access
    global append1
    global append2
    global connections
    global prec_final
#     n = sig.shape[0]
#     print index
    n = len(index)
    if n==3:# and extra == 1) or (n==4 and extra == 1):
        
        prec = np.ones((3,3))
        non_center = [0,1,2]
        non_center.remove(center_3node)
        prec[non_center[0], non_center[1]] = 0
        prec[non_center[1], non_center[0]] = 0
        return prec
    if n==2:# and extra == 0) or (n==3 and extra == 1):
        prec = np.array([[1,1],[1,1]])
        return prec
    if n==1:# and extra == 0) or (n==2 and extra == 1):
        prec = np.array([[1]])
        return prec
    if n==0:# and extra ==0) or (n==1 and extra == 1):
        prec = np.array([[]])
        return prec         
    sub_sig = sig[np.ix_(index, index)]
    part1, part2, conn1, conn2 = split(sub_sig)
    index1 = [index[i]for i in part1]
    index2 = [index[i]for i in part2]

    n1 = len(part1)
    n2 = len(part2) 
#     if first_access == 1:
#         append1 = part2[0]
#         append2 = part1[0]
#         first_access = 0
#     if extra == 1:
#         if n-1 in part1:
#             part1.remove(n-1)
#             if conn1 == n-1 :#and len(part1)>0
#                 conn1 = part1[0]
#         else:
#             part2.remove(n-1)
#             if conn2 == n-1 :#and len(part1)>0
#                 conn2 = part2[0]
#     print part1, part2, conn1, conn2, "part1, part2, conn1, conn2"
    cand_conns1, cand_conns2 = candidate_connections(sub_sig, part1, part2, conn1, conn2) 
#     print cand_conns1, cand_conns2, "cand_conns1, cand_conns2"
    cand_conns1 = [index[i] for i in cand_conns1]
    conn1 = index[conn1]
    conn1 = check_candidates(sig, connections, cand_conns1, conn1, index2)
    cand_conns2 = [index[i] for i in cand_conns2]
    conn2 = index[conn2]
    conn2 = check_candidates(sig, connections, cand_conns2, conn2, index1)
    print index1, index2, conn1, conn2,cand_conns1, cand_conns2,"index1, index2, conn1, conn2, cand_conns1 , cand_conns2"
    if conn1 not in connections:
        connections.append(conn1)
    if conn2 not in connections:
        connections.append(conn2)
    conn1_pos = index.index(conn1)
    conn2_pos = index.index(conn2)
    if n1 == 3:
        if len(cand_conns1) == 2:
#             print "arrival 1"
            for i in range(3):
                if conn1_pos == part1[i]:
                    prec1 = learn_tree(sig, index1,i )                    
        else:
#             print "arrival 2"
            sub_index = [-1,-1,-1,-1,-1]
            sub_index[0:3] = index1[:]
            sub_index[3] = conn2#index2[0]
            for i in connections:
                if i in sub_index:
                    continue
                sub_index[4] = i
                sub_sig = sig[np.ix_(sub_index, sub_index)]
                status = check_5node_MC_structure(sub_sig)
                if status == True:
                    
                    mid = mid_element_5MC(sub_sig)
#                     print sub_index, mid, "sub_index, mid"
                    prec1 = learn_tree(sig, index1,mid )
            
            
    else:
        prec1 = learn_tree(sig, index1)
#             k = part1[0]
#             part1[0] = part1[1]
#             part1[1] = k
#         if conn1_pos == part1[2]:
#             k = part1[2]
#             part1[2] = part1[1]
#             part1[1] = k
    if n2 == 3:
        if len(cand_conns2) == 2:
#             print "arrival 3"
            for i in range(3):
                if conn2_pos == part2[i]:
                    prec2 = learn_tree(sig, index2,i )
        else:
#             print "arrival 4"
            sub_index = [-1,-1,-1,-1,-1]
            sub_index[0:3] = index2[:]
            sub_index[3] = conn1#index1[0]
            for i in connections:
                if i in sub_index:
                    continue
                sub_index[4] = i
                
                sub_sig = sig[np.ix_(sub_index, sub_index)]
                status = check_5node_MC_structure(sub_sig)
                if status == True:
                    mid = mid_element_5MC(sub_sig)
#                     print sub_index, mid, "sub_index, mid"
                    prec2 = learn_tree(sig, index2,mid)
            
            
    else:
        prec2 = learn_tree(sig, index2)
#         if conn2_pos == part2[0]:
#             k = part2[0]
#             part2[0] = part2[1]
#             part2[1] = k
#         if conn2_pos == part2[2]:
#             k = part2[2]
#             part2[2] = part2[1]
#             part2[1] = k
#     prec1 = learn_tree(sig, index1)
#     prec2 = learn_tree(sig, index2)
#     learn_tree(sig, index1)
#     learn_tree(sig, index2)
#     prec_final[np.ix_(index1, index1)]
    print prec1, "prec1"
    print prec2, "prec2"
    prec_comb = np.zeros((n,n))
    conn1_pos = index.index(conn1)
    conn2_pos = index.index(conn2)
#     if n1 == 3 and len(cand_conns1) == 2:
#         if conn1_pos == part1[0]:
#             k = part1[0]
#             part1[0] = part1[1]
#             part1[1] = k
#         if conn1_pos == part1[2]:
#             k = part1[2]
#             part1[2] = part1[1]
#             part1[1] = k
#     if n2 == 3 and len(cand_conns2) == 2:
# #         if conn1_pos == 0:
#         if conn2_pos == part2[0]:
#             k = part2[0]
#             part2[0] = part2[1]
#             part2[1] = k
#         if conn2_pos == part2[2]:
#             k = part2[2]
#             part2[2] = part2[1]
#             part2[1] = k
            
    prec_comb[np.ix_(part1, part1)] = prec1[:, :]
    prec_comb[np.ix_(part2, part2)] = prec2[:, :]
    
    prec_comb[conn1_pos, conn2_pos] = 1
    prec_comb[conn2_pos, conn1_pos] = 1
    
    print prec_comb, "combined",n, "n"
    return prec_comb
    
#     leaf1 = 1
#     leaf2 = 1
#     if n1>=2 and n2>=2:
#         leaf1, leaf2 = check_leaf(sig, part1, part2, conn1, conn2)
    
#     extra_new = 0
#     indicator = 0 
#     print part1, part2, conn1, conn2, n, "part1, part2, conn1, conn2, n"
#     if (n1>1 and n2 > 1):
#         if major_group == 0:
#             part1.append(append1)
# # #         part1 = [part2[1]] + part1
#             part2.append(append2)
# #         part2 = [part1[1]] + part2
# #         part2.append(part1[1])
#         if major_group == 1:
#             part1.append(append1)
#             part2.append(append1)
#         if major_group == 2:
#             part1.append(append2)
#             part2.append(append2)
#         extra_new = 1
#     sig1 = sig[np.ix_(part1, part1)]
#     sig2 = sig[np.ix_(part2, part2)]
#     if (n1>1 and n2 > 1):
#         if major_group == 0:
#             part1.remove(append1)
# # #         part1 = [part2[1]] + part1
#             part2.remove(append2)
# #         part2 = [part1[1]] + part2
# #         part2.append(part1[1])
#         if major_group == 1:
#             part1.remove(append1)
#             part2.remove(append1)
#         if major_group == 2:
#             part1.append(append2)
#             part2.append(append2)
#     if major_group == 0:
#         major_group_arg = 1
#     else:
#         major_group_arg = major_group
#     prec1 = learn_tree(sig1, extra_new, major_group_arg)
#     conn1_index = part1.index(conn1)
#     if leaf1 == 1 and n1>=2 and n2>=2:
#         if check_leaf_prec(prec1, conn1_index) == False:
#             exchange_leaf_internal(prec1, conn1_index)
        
#     print prec1, "part 1", n, "n"
#     if major_group == 0:
#         major_group_arg = 2
#     else:
#         major_group_arg = major_group
#     prec2 = learn_tree(sig2, extra_new, major_group_arg)
#     conn2_index = part2.index(conn2)
#     if leaf2 == 1 and n1>=2 and n2>=2:
#         if check_leaf_prec(prec2, conn2_index) == False:
#             exchange_leaf_internal(prec2, conn2_index)
#     print prec2, "part 2", n, "n"
#     if extra == 1:
#         n = n-2
    

In [34]:

def inverse_perm(perm):
    inverse = [0] * len(perm)
    for i, p in enumerate(perm):
        inverse[p] = i
    inverse = np.array(inverse)
    return inverse


In [35]:
 """
Generating 15 node binary tree
"""
rand.seed(6)
n = 15
sparsity = np.array([1, 1,\
                     0, 0, 1, 0, 0, 1,\
                     0,0 , 0, 0, 1, 0, 0, 0, 0, 1,\
                     0, 0 ,0, 0, 0, 0,1, 0, 0 ,0, 0, 0, 0,1,\
                     0, 0 ,0, 0, 0, 0, 0, 0,1, 0, 0 ,0, 0, 0, 0, 0, 0,1,\
                     0, 0 ,0, 0, 0, 0, 0, 0, 0,0, 1,0, 0 ,0, 0, 0, 0, 0, 0, 0,0, 1,\
                     0, 0 ,0, 0, 0, 0, 0, 0,0,0, 0,0, 1,0, 0 ,0, 0, 0, 0, 0, 0, 0,0,0,0, 1,\
                     0,0,0,0,0,0,0])

# sparsity = np.reshape(sparsity, 21)
sparsity = sparsity.flatten()
# print sparsity.shape
theta , sparsity = specific_sparsity_theta(n, sparsity)
sig = inv(theta)
# print type(sig)
noise_vec = rand.uniform(1,1.2, size = [n,])
noise = np.diag(noise_vec)
sig_noisy = sig + noise
# print sig_noisy
index = [0,5, 6, 11, 14]

sig_noisy1 = sig_noisy[np.ix_(index, index)]
status = check_5node_MC_structure(sig_noisy1)
# print status 
perm = np.random.permutation(n)
print perm
sig_noisy = sig_noisy[np.ix_(perm, perm)]
# print sig_noisy
# index = [0,1,2,5,6,11, 12, 13, 14]

# index = [0, 1, 3, 4, 7, 8, 9, 10]
index = [0,2,5,6,11,12, 13, 14]
sig_noisy2 = sig_noisy[np.ix_(index, index)]
# print sig_noisy2
# print mid_element_5MC(sig_noisy2)
# print sig_noisy
# print"check print"
part1, part2, conn1, conn2= split(sig_noisy2)

cand_conns1, cand_conns2 = candidate_connections(sig_noisy2, part1, part2, conn1, conn2)
connections = [0,1]
conn = index[conn1]
cand_conns = [index[i] for i in cand_conns1]
group = [index[i] for i in part2]
conn1 = check_candidates(sig_noisy, connections, cand_conns, conn, group)
# leaf1, leaf2 = check_leaf(sig_noisy2, part1, part2, conn1, conn2)
# print part1, part2, conn1, conn2, cand_conns1, cand_conns2
n = sig_noisy.shape[0]
# prec_final = -1*np.ones((n,n))
index = range(sig_noisy.shape[0])
prec = learn_tree(sig_noisy, index)
prec1 = prec[np.ix_(perm, perm)]
inv_perm = inverse_perm(perm)
prec2 = prec[np.ix_(inv_perm, inv_perm)]
# print prec, "prec"
# print prec1, "prec1"
print prec2, "prec2"
# prec = learn_tree(sig_noisy)
# print prec
# print perm
# perm1 = np.array(perm1)
# # part1 = np.array(part1)
# # part2 = np.array(part2)
# # part1.append(part2[0])
# # part2.append(part1[0])
# # print sig_noisy
# # print part1, part2, perm1 , "before"
# # inv_perm = inverse_perm(perm1)
# part1 = perm1[np.ix_(part1)]
# part2 = perm1[np.ix_(part2)]
# print part1
# print part2, "after"#, inv_perm
# # print perm1
# connections = find_connecting_nodes(sig_noisy1, part1, part2,1)
# # print sig_noisy
# # print perm1
# # print sig_noisy
# print connections


[ 1  6  7  3  4 13  5  8 12 11  0  2  9 10 14]
[0, 1, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14] [2, 3, 7] 0 3 [11] [2, 7] index1, index2, conn1, conn2, cand_conns1 , cand_conns2
[0, 4, 12, 13] [1, 5, 6, 8, 9, 10, 11, 14] 0 10 [13] [] index1, index2, conn1, conn2, cand_conns1 , cand_conns2
[0, 4, 12] [13] 4 13 [0, 12] [] index1, index2, conn1, conn2, cand_conns1 , cand_conns2
[[ 1.  1.  0.]
 [ 1.  1.  1.]
 [ 0.  1.  1.]] prec1
[[1]] prec2
[[ 1.  1.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  0.  1.]] combined 4 n
[1, 5, 14] [6, 8, 9, 10, 11] 5 11 [1, 14] [9, 10] index1, index2, conn1, conn2, cand_conns1 , cand_conns2
[10, 11] [8, 6, 9] 11 6 [10] [8, 9] index1, index2, conn1, conn2, cand_conns1 , cand_conns2
[[1 1]
 [1 1]] prec1
[[ 1.  1.  0.]
 [ 1.  1.  1.]
 [ 0.  1.  1.]] prec2
[[ 1.  1.  1.  0.  1.]
 [ 1.  1.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.]
 [ 1.  0.  0.  1.  1.]] combined 5 n
[[ 1.  1.  0.]
 [ 1.  1.  1.]
 [ 0.  1.  1.]] prec1
[[ 1.  1.  1.  0.  1.]


In [36]:
def find_connecting_nodes(sig, group1, group2, indicator = 0):
    print group1, group2, indicator
    n1 = len(group1)
    n2 = len(group2)
    connections = [-1, -1]
#     print n1,"1"
    if (n2 <= 4 and indicator ==2 ) or (n2 <= 3 and indicator == 0):
        connections[1] = group2[0]
    else:
        index = []
        used = []
        unused = range(n2)
    #     if n1<n2:
        index.append(group1[0])
        index.append(group1[1])
        random = np.random.permutation(n2)
    #     index.append(group2[random[0]])
    #     index.append(group2[random[1]])
    #     index.append(group2[random[2]])
        for i in range(3):
            index.append(group2[random[i]])
        sub_sig = sig[np.ix_(index, index)]
        while(check_5node_MC_structure(sub_sig) == False):
            for i in range(3):
                index.remove(group2[random[i]])
            random = np.random.permutation(n2)
            for i in range(3):
                index.append(group2[random[i]])
            sub_sig = sig[np.ix_(index, index)]
        for i in range(3):
            used.append(random[i])
            unused.remove(random[i])
        print index
        mid = mid_element_5MC(sub_sig)
#         if index[mid]!= group2[n2-1]:
        print mid
        if indicator == 0:
            connections[1] = index[mid]
        elif mid != n-1:
            connections[1] = index[mid]
        
#         if mid != n-1 or indicator !=0:
#             connections[1] = index[mid]
#         connections[1] = index[mid]
        res = 0
        while unused:
            check = 0
            for i in unused:
                res =  index[2+(mid-1)%3]
                index[2+(mid-1)%3] =group2[i]
                sub_sig = sig[np.ix_(index, index)]
                if (check_5node_MC_structure(sub_sig) == True):
                    check = 1
                    break
                else:
                    index[2+(mid-1)%3] = res
                    index[2+(mid)%3] =group2[i]
                    sub_sig = sig[np.ix_(index, index)]
                    if (check_5node_MC_structure(sub_sig) == True):
                        check = 1
                        break
            if check == 0:
                break
#                 return connections
#             print index, mid
#             if index[mid]!= group2[n2-1]:
            mid = mid_element_5MC(sub_sig)
    #         print mid
            if indicator == 0:
                connections[1] = index[mid]
            elif mid != n-1:
                connections[1] = index[mid]
            for i in range(3):
                if i+2 != mid:
                    if index[i+2] in unused:
                        unused.remove(index[i+2])
            print unused
#     print n1,"2"
    if (n1 <= 4 and indicator == 1) or (n1 <= 3 and indicator == 0):
#         print "check"
        connections[0] = group1[0]
    else:
            
        index = []
        used = []
        unused = range(n1)
    #     if n1<n2:
        index.append(group2[0])
        index.append(group2[1])
        random = np.random.permutation(n1)
    #     index.append(group2[random[0]])
    #     index.append(group2[random[1]])
    #     index.append(group2[random[2]])
        for i in range(3):
            index.append(group1[random[i]])
        sub_sig = sig[np.ix_(index, index)]
        while(check_5node_MC_structure(sub_sig) == False):
            for i in range(3):
                index.remove(group1[random[i]])
            random = np.random.permutation(n1)
            for i in range(3):
                index.append(group1[random[i]])
            sub_sig = sig[np.ix_(index, index)]
        for i in range(3):
            used.append(random[i])
            unused.remove(random[i])
        print index#, sub_sig
        
        mid = mid_element_5MC(sub_sig)
        print mid
    #     print mid
#         if index[mid]!= group1[n1-1]:
#         connections[0] = index[mid]
        if indicator == 0:
            connections[0] = index[mid]
        elif mid != n-1:
            connections[0] = index[mid]
        while unused:
            check = 0
            for i in unused:
                res =  index[2+(mid-1)%3]
                index[2+(mid-1)%3] =group1[i]
                sub_sig = sig[np.ix_(index, index)]
                if (check_5node_MC_structure(sub_sig) == True):
                    check = 1
                    break
                else:
                    index[2+(mid-1)%3] = res
                    index[2+(mid)%3] =group1[i]
                    sub_sig = sig[np.ix_(index, index)]
                    if (check_5node_MC_structure(sub_sig) == True):
                        check = 1
                        break
            if check == 0:
                break
            else:
                mid = mid_element_5MC(sub_sig)
#                 return connections
            print index
            mid = mid_element_5MC(sub_sig)
            print mid
#             if index[mid]!= group1[n1-1]:
            if indicator == 0:
                connections[0] = index[mid]
            elif mid != n-1:
                connections[0] = index[mid]
#             connections[0] = index[mid]
            for i in range(3):
                if i+2 != mid:
                    if index[i+2] in unused:
                        unused.remove(index[i+2])
# #     mid_index = group2.index(index[mid])
#     for i in range(n2):
#         if i in prev_index:
#             continue
#         index[2+(mid-1)%3] =group2[i]
#         print index
#         sub_sig = sig[np.ix_(index, index)]
# #         n3 = len(unused)
#         while (check_5node_MC_structure(sub_sig) == False):
#             new_ind = np.random.randint(len(unused))
#             new_ind = unused[new_ind]
            
#             index[2+(mid-1)%3] =group2[new_ind]
#             sub_sig = sig[np.ix_(index, index)]
#             print index
#         print unused,"unused"
#         prev_index.append(new_ind)
#         unused.remove(unused[new_ind])
# #             continue
# #         else:
#         mid = mid_element_5MC(sub_sig)

#         print index, mid, "index, mid"
#         connections[1] = index[mid]
#             mid_index = group2.index(index[mid])
    return connections
        
        
        
        
        
        
        

In [37]:
index = [0,1,2,5,6,11, 12, 13, 14]
sig_noisy1 = sig_noisy[np.ix_(index, index)]
part1, part2, perm1 = split(sig_noisy1)
perm1 = np.array(perm1)
part1 = perm1[np.ix_(part1)]
part2 = perm1[np.ix_(part2)]
print part1
print part2, "after"#, inv_perm
connections = find_connecting_nodes(sig_noisy1, part1, part2,0)

print connections

ValueError: too many values to unpack

In [ ]:
"""
## Random Tests!
index = [4,13,5,10]
sub_sig = sig_noisy[np.ix_(index, index)]
# print sub_sig
print check_4node_star_structure(sub_sig), "Star"
status, pair = check_4node_MC_structure(sub_sig)#, "MC"
if status == True:
    print "MC", pair
# print theta
"""

In [ ]:

def learn_tree1(sig, extra = 0):

    n = sig.shape[0]
    if (n==3 and extra == 0) or (n==5 and extra == 1):
        prec = np.array([[1,1,0],[1,1,1],[0,1,1]])
        return prec
    if (n==2 and extra == 0) or (n==4 and extra == 1):
        prec = np.array([[1,1],[1,1]])
        return prec
    if (n==1 and extra == 0) or (n==3 and extra == 1):
        prec = np.array([[1]])
        return prec
    if (n==0 and extra ==0) or (n==2 and extra == 1):
        prec = np.array([[]])
        return prec
#     if n==4:
#         pair, status = check_4node_MC_structure(sig)            
    part1, part2, conn1, conn2 = split(sig)
    n1 = len(part1)
    n2 = len(part2) 
    
    if extra == 1:
        while (len(part1) == 2 and  n-1 in part1) or (len(part2) == 2 and n-1 in part2):
            part1, part2, conn1, conn2 = split(sig)
        if n-1 in part1:
#             pos_temp1 = np.where(part1 == n-1)
#             pos_temp2 = pos_temp1[0]
#             pos = pos_temp2[0]
#             part1 = np.delete(part1, pos)
            part1.remove(n-1)
            part1.remove(0)
            if (conn1 == n-1 or conn1 == n-2) and len(part1)>0:
                conn1 = part1[0]
            n1 = n1-2
        if n-1 in part2:
#             pos_temp1 = np.where(part2 == n-1)
#             pos_temp2 = pos_temp1[0]
#             pos = pos_temp2[0]
#             part2 = np.delete(part2, pos) 
            part2.remove(n-1)
            part2.remove(0)
            if (conn2 == n-1 or conn2 == n-2) and len(part2)>0:
                conn2 = part2[0]
            n2 = n2-2
    leaf1 = 1
    leaf2 = 1
    if n1>=2 and n2>=2:
        leaf1, leaf2 = check_leaf(sig, part1, part2, conn1, conn2)
    
    extra_new = 0
    indicator = 0 
    print part1, part2, conn1, conn2, n, "part1, part2, conn1, conn2, n"
    if (n1>2 and n2 > 2):
        part1.append(part2[0])
        part1 = [part2[1]] + part1
        part2.append(part1[0])
        part2 = [part1[1]] + part2
#         part2.append(part1[1])
        extra_new = 1
    sig1 = sig[np.ix_(part1, part1)]
    sig2 = sig[np.ix_(part2, part2)]
    if (n1>2 and n2 > 2):
        part1.remove(part2[0])
        part2.remove(part1[0])
        part1.remove(part2[1])
        part2.remove(part1[1])
#     check1 = 0
#     check2 = 0
    
#     if n1 == 4:
        
#         status, pair = check_4node_MC_structure(sig1)
#         if status == False:
#             prec1 = np.zeros((4,4))
#             part1.append(part2[0])
#             part1.append(part2[1])
#             sig1 = sig[np.ix_(part1, part1)]
#             part1a, part2a, conn1a, conn2a = split(sig1)
# #             if len(part1a) == 2:
#             part1a.remove(4)
#             part1a.remove(5)
#             prec1[np.ix_(part2a, part2a)] = np.array([[1,1,0],[1,1,1],[0,1,1]])
#             prec1[part2a[1],part1a[0]] = 1
#             prec1[part1a[0],part2a[1]] = 1
#             prec1[part1a[0],part1a[0]] = 1
# #             else:
# #                 part2a.remove(4)
# #                 prec1[np.ix_(part1a, part1a)] = np.array([[1,1,0],[1,1,1],[0,1,1]])
# #                 prec1[part1a[1],part2a[0]] = 1
# #                 prec1[part2a[0],part1a[1]] = 1
# #                 prec1[part2a[0],part2a[0]] = 1
#             check1 = 1
#             part1.remove(part2[0])
#             part1.remove(part2[1])
#     if n1 == 5:        
#         status = check_5node_MC_structure(sig1)
#         prec1 = np.zeros((n1,n1))
        
#         if status == False:
#             success = 0
#             part1.append(part2[0])
#             sig1 = sig[np.ix_(part1, part1)]
#             sig1_copy = np.zeros((6,6))
#             sig1_copy[:,:] = sig1[:,:]
#             perm = range(6)
#             new_node = 5
#             while success == 0:
                
                
                
#                 part1a, part2a, conn1a, conn2a = split(sig1)
#                 if new_node in part1a:
#                     if len(part1a) < 3:
#                         sig1[:,:] = sig1_copy[:,:]
#                         perm = np.random.permutation(6)
#                         inv_perm = inverse_perm(perm)
#                         new_node = inv_perm[5]
#                         sig1[:,:] = sig1[np.ix_(perm, perm)]
#                         continue
#                     else:
#                         success = 1
#                     perm = np.array(perm)
#                     part1a = perm[np.ix_(part1a)]
#                     conn1a = perm[conn1a]
#                     part2a = perm[np.ix_(part2a)]
#                     conn2a = perm[conn2a]
#                     part1a.remove(5)
#                     prec1[np.ix_(part2a, part2a)] = np.array([[1,1,0],[1,1,1],[0,1,1]])
#                     prec1[part2a[1],part1a[0]] = 1
#                     prec1[part1a[0],part2a[1]] = 1
#                     prec1[part1a[0],part1a[0]] = 1
#                 else:
#                     if len(part2a) < 3:
#                         sig2[:,:] = sig2_copy[:,:]
#                         perm = np.random.permutation(6)
#                         inv_perm = inverse_perm(perm)
#                         new_node = inv_perm[5]
#                         sig2[:,:] = sig2[np.ix_(perm, perm)]
#                         continue
#                     else:
#                         success = 1
#                     perm = np.array(perm)
#                     part1a = perma[np.ix_(part1a)]
#                     part2a = perma[np.ix_(part2a)]
#                     part1a.remove(5)
#                     prec1[np.ix_(part2a, part2a)] = np.array([[1,1,0],[1,1,1],[0,1,1]])
#                     prec1[part2a[1],part1a[0]] = 1
#                     prec1[part1a[0],part2a[1]] = 1
#                     prec1[part1a[0],part1a[0]] = 1
#             check1 = 1
#             part1.remove(part2[0])
#     if n2 == 4:
#         print "check_arrival1"
#         prec2 = np.zeros((4,4))
#         status, pair = check_4node_MC_structure(sig2)
#         print status
#         if status == False:
#             print "check_arrival2"
#             part2.append(part1[0])
#             sig2 = sig[np.ix_(part2, part2)]
#             part1a, part2a, conn1a, conn2a = split(sig2)
#             if len(part1a) == 2:
#                 part1a.remove(4)
#                 prec2[np.ix_(part2a, part2a)] = np.array([[1,1,0],[1,1,1],[0,1,1]])
#                 prec2[part2a[1],part1a[0]] = 1
#                 prec2[part1a[0],part2a[1]] = 1
#                 prec2[part1a[0],part1a[0]] = 1
#             else:
#                 part2a.remove(4)
#                 prec2[np.ix_(part1a, part1a)] = np.array([[1,1,0],[1,1,1],[0,1,1]])
#                 prec2[part1a[1],part2a[0]] = 1
#                 prec2[part2a[0],part1a[1]] = 1
#                 prec2[part2a[0],part2a[0]] = 1
#             check2 = 1
#             part2.remove(part1[0])
#     if n2 == 5:        
#         status = check_5node_MC_structure(sig2)
#         prec1 = np.zeros((n2,n2))
        
#         if status == False:
#             success = 0
#             part2.append(part1[0])
#             sig2 = sig[np.ix_(part2, part2)]
#             sig2_copy = np.zeros((6,6))
#             sig2_copy[:,:] = sig2[:,:]
#             perm = range(6)
#             new_node = 5
#             while success == 0:
                
                
                
#                 part1a, part2a, conn1a, conn2a = split(sig2)
#                 if new_node in part1a:
#                     if len(part1a) < 3:
#                         sig2[:,:] = sig2_copy[:,:]
#                         perm = np.random.permutation(6)
#                         inv_perm = inverse_perm(perm)
#                         new_node = inv_perm[5]
#                         sig2[:,:] = sig2[np.ix_(perm, perm)]
#                         continue
#                     else:
#                         success = 1
#                     perm = np.array(perm)
#                     part1a = perm[np.ix_(part1a)]
#                     part2a = perm[np.ix_(part2a)]
#                     part1a.remove(5)
#                     prec1[np.ix_(part2a, part2a)] = np.array([[1,1,0],[1,1,1],[0,1,1]])
#                     prec1[part2a[1],part1a[0]] = 1
#                     prec1[part1a[0],part2a[1]] = 1
#                     prec1[part1a[0],part1a[0]] = 1
#                 else:
#                     if len(part2a) < 3:
#                         sig2[:,:] = sig2_copy[:,:]
#                         perm = np.random.permutation(6)
#                         inv_perm = inverse_perm(perm)
#                         new_node = inv_perm[5]
#                         sig2[:,:] = sig2[np.ix_(perm, perm)]
#                         continue
#                     else:
#                         success = 1
#                     perm = np.array(perm)
#                     part1a = perma[np.ix_(part1a)]
#                     part2a = perma[np.ix_(part2a)]
#                     part1a.remove(5)
#                     prec1[np.ix_(part2a, part2a)] = np.array([[1,1,0],[1,1,1],[0,1,1]])
#                     prec1[part2a[1],part1a[0]] = 1
#                     prec1[part1a[0],part2a[1]] = 1
#                     prec1[part1a[0],part1a[0]] = 1
#             check1 = 1
#             part1.remove(part2[0])
#     if check1 == 0:
    prec1 = learn_tree(sig1, extra_new)
    conn1_index = part1.index(conn1)
    if leaf1 == 1 and n1>=2 and n2>=2:
        if check_leaf_prec(prec1, conn1_index) == False:
            exchange_leaf_internal(prec1, conn1_index)
        
    print prec1, "part 1", n, "n"
#     if check2 == 0:
    prec2 = learn_tree(sig2, extra_new)
    conn2_index = part2.index(conn2)
    if leaf2 == 1 and n1>=2 and n2>=2:
        if check_leaf_prec(prec2, conn2_index) == False:
            exchange_leaf_internal(prec2, conn2_index)
    print prec2, "part 2", n, "n"
    if extra == 1:
        n = n-2
    prec_comb = np.zeros((n,n))
    prec_comb[np.ix_(part1, part1)] = prec1[:, :]
    prec_comb[np.ix_(part2, part2)] = prec2[:, :]
    prec_comb[conn1, conn2] = 1
    prec_comb[conn2, conn1] = 1
#     prec_comb[perm[connections[0]], perm[connections[1]]] = 1
#     prec_comb[perm[connections[1]], perm[connections[0]]] = 1
#     if extra == 1:
#         comb_part = np.concatenate((part1, part2))
#         pos_temp1 = np.where(comb_part == n-1)
#         pos_temp2 = pos_temp1[0]
#         pos = pos_temp2[0]
# #         print pos
#         prec_comb = np.delete(prec_comb, pos, 0)
#         prec_comb = np.delete(prec_comb, pos, 1)
    print prec_comb, "combined",n, "n"
    return prec_comb

In [ ]:
"""
In this block we check if the 4 node star structure works or not.
sig_noisy1 is the noisy covariance matrix for a star structure
sig_noisy2 is the noisy covariance matrix for a MC structure

"""
"""
n = 4
rand.seed(1)
sparsity = np.array([0,0,0,1,1,1])
theta1, zeros = specific_sparsity_theta(n, sparsity)
theta2, zeros = tridiagonal_theta(n)
# print inv(theta)
sig1 = inv(theta1)
sig2 = inv(theta2)
# print sig1
noise_vec1 = rand.uniform(1,1.2, size = [n,])
noise1 = np.diag(noise_vec1)
noise_vec2 = rand.uniform(1,1.2, size = [n,])
noise2 = np.diag(noise_vec2)
# print noise
sig_noisy1 = sig1 + noise1
sig_noisy2 = sig2 + noise2

print check_4node_star_structure(sig_noisy1)
print check_4node_star_structure(sig_noisy2)
# print check_4node_MC_structure(sig_noisy1)
print check_4node_MC_structure(sig_noisy1)
"""

In [ ]:
"""
Checking the properties of 7 node binary tree

sparsity = np.array([1, 1, 0, 0, 1, 0, 0, 1, 0,0 , 0, 0, 1, 0, 0, 0, 0, 1, 0, 0 ,0])
# sparsity = np.reshape(sparsity, 21)
sparsity = sparsity.flatten()
# print sparsity
theta , sparsity = specific_sparsity_theta(7, sparsity)
sig = inv(theta)
index = [5,6,3,4]
sub_sig = sig[np.ix_(index, index)]
# print sub_sig
print check_4node_star_structure(sub_sig)
print check_4node_MC_structure(sub_sig)
# print theta
"""

In [ ]:
index = [10, 11, 2, 3, 7]
sub_sig = sig_noisy[np.ix_(index, index)]
print check_5node_MC_structure(sub_sig)

In [ ]:

rand.seed(2)
perm = np.random.permutation(n)
print perm

In [ ]:
"""
def learn_tree(sig, extra = 0):
    n = sig.shape[0]
    extra_new = 0
    print n, "n"
    if (n==3 and extra == 0) or (n==4 and extra == 1):
        prec = np.array([[1,1,0],[1,1,1],[0,1,1]])
        return prec
    if (n==2 and extra == 0) or (n==3 and extra == 1):
        prec = np.array([[1,1],[1,1]])
        return prec
    if (n==1 and extra == 0) or (n==2 and extra == 1):
        prec = np.array([[1]])
        return prec
#     if n==4:
    part1, part2, perm = split(sig)
    n1 = len(part1)
    n2 = len(part2)
#     print n1, n2, n, "n1 n2 n"
    perm = np.array(perm)
    part1 = perm[np.ix_(part1)]
    part2 = perm[np.ix_(part2)]
    indicator = 0 
    if extra == 1:
        if n-1 in part1:
            indicator = 1
        else:
            indicator = 2
#     print part1, "part1", part2, "part2"
#     inv_perm = inverse_perm(perm)
    connections = find_connecting_nodes(sig, part1, part2, indicator)
    if (n1!=1 and n2 != 1):
        part1 = np.append(part1, part2[0])
        part2 = np.append(part2, part1[0])
        extra_new = 1
#     print part1, "part1", part2, "part2", "middle"
#     connections = find_connecting_nodes(sig, part1, part2)
#     part1 = np.delete(part1, n1)
#     part2 = np.delete(part2, n2)
#     part1 = np.setdiff1d(part1, part2[0])
#     part2 = np.setdiff1d(part2, part1[0])
    print part1, "part1", part2, "part2", "after"
    print connections, "connections"
#     ind1 = perm[np.ix_(part1)]
#     ind2 = perm[np.ix_(part2)]
#     print ind2
    sig1 = sig[np.ix_(part1, part1)]
    sig2 = sig[np.ix_(part2, part2)]
    prec1 = learn_tree(sig1, extra_new)
    print prec1, "part 1", n, "n"
    prec2 = learn_tree(sig2, extra_new)
    print prec2, "part 2", n, "n"
    if (n1!=1 and n2 != 1):
        part1 = np.delete(part1, n1)
        part2 = np.delete(part2, n2)
#     if extra == 1:
#         prec_comb = np.zeros((n-1,n-1))
#         if n-1 in part1:
#             part1 = np.setdiff1d(part1,[n-1])
#         prec_comb[np.ix_(part1, part1)] = prec1[:, :]
#     #     print ind2, n, "index 2, n"
#     #     print prec2
#         if n-1 in part2:
#             part2 = np.setdiff1d(part2,[n-1])
#         prec_comb[np.ix_(part2, part2)] = prec2[:, :]
#         prec_comb[perm[connections[0]], perm[connections[1]]] = 1
#         prec_comb[perm[connections[1]], perm[connections[0]]] = 1
#         print prec_comb, "combined",n, "n"
#     else:
    prec_comb = np.zeros((n,n))
    prec_comb[np.ix_(part1, part1)] = prec1[:, :]
#     print ind2, n, "index 2, n"
#     print prec2

    prec_comb[np.ix_(part2, part2)] = prec2[:, :]
    prec_comb[perm[connections[0]], perm[connections[1]]] = 1
    prec_comb[perm[connections[1]], perm[connections[0]]] = 1
    if extra == 1:
        comb_part = np.concatenate((part1, part2))
        pos_temp1 = np.where(comb_part == n-1)
        pos_temp2 = pos_temp1[0]
        pos = pos_temp2[0]
#         print pos
        prec_comb = np.delete(prec_comb, pos, 0)
        prec_comb = np.delete(prec_comb, pos, 1)
    print prec_comb, "combined",n, "n"
    return prec_comb
"""

In [ ]:
full = [0,1,2,3]
pair = [0,2]
full.remove(pair[0])
full.remove(pair[1])
print full

In [ ]:
"""
def learn_tree(sig, extra = 0):
    n = sig.shape[0]
    extra_new = 0
    print n, "n", extra, "extra"
    if (n==3 and extra == 0) or (n==4 and extra == 1):
        prec = np.array([[1,1,0],[1,1,1],[0,1,1]])
        return prec
    if (n==2 and extra == 0) or (n==3 and extra == 1):
        prec = np.array([[1,1],[1,1]])
        return prec
    if (n==1 and extra == 0) or (n==2 and extra == 1):
        prec = np.array([[1]])
        return prec
#     if n==4:
    part1, part2 = split(sig)
    n1 = len(part1)
    n2 = len(part2)
#     print n1, n2, n, "n1 n2 n"
#     perm = np.array(perm)
#     part1 = perm[np.ix_(part1)]
#     part2 = perm[np.ix_(part2)]
    indicator = 0 
    if extra == 1:
        if n-1 in part1:
            indicator = 1
        else:
            indicator = 2
#     print part1, "part1", part2, "part2"
#     inv_perm = inverse_perm(perm)
    connections = find_connecting_nodes(sig, part1, part2, indicator)
    print connections, "connections"
    if extra == 1:
#         comb_part = np.concatenate((part1, part2))
        
        if n-1 in part1:
            pos_temp1 = np.where(part1 == n-1)
            pos_temp2 = pos_temp1[0]
            pos = pos_temp2[0]
            part1 = np.delete(part1, pos)
            n1 = n1-1
        if n-1 in part2:
            pos_temp1 = np.where(part2 == n-1)
            pos_temp2 = pos_temp1[0]
            pos = pos_temp2[0]
            part2 = np.delete(part2, pos)    
            n2 = n2-1
        
    if (n1!=1 and n2 != 1):
        part1 = np.append(part1, part2[0])
        part2 = np.append(part2, part1[0])
        extra_new = 1
#     print part1, "part1", part2, "part2", "middle"
#     connections = find_connecting_nodes(sig, part1, part2)
#     part1 = np.delete(part1, n1)
#     part2 = np.delete(part2, n2)
#     part1 = np.setdiff1d(part1, part2[0])
#     part2 = np.setdiff1d(part2, part1[0])
    print part1, "part1", part2, "part2", "after"

#     ind1 = perm[np.ix_(part1)]
#     ind2 = perm[np.ix_(part2)]
#     print ind2
    sig1 = sig[np.ix_(part1, part1)]
    sig2 = sig[np.ix_(part2, part2)]
    prec1 = learn_tree(sig1, extra_new)
    print prec1, "part 1", n, "n"
    prec2 = learn_tree(sig2, extra_new)
    print prec2, "part 2", n, "n"
    if (n1!=1 and n2 != 1):
        part1 = np.delete(part1, n1)
        part2 = np.delete(part2, n2)
#     if extra == 1:
#         prec_comb = np.zeros((n-1,n-1))
#         if n-1 in part1:
#             part1 = np.setdiff1d(part1,[n-1])
#         prec_comb[np.ix_(part1, part1)] = prec1[:, :]
#     #     print ind2, n, "index 2, n"
#     #     print prec2
#         if n-1 in part2:
#             part2 = np.setdiff1d(part2,[n-1])
#         prec_comb[np.ix_(part2, part2)] = prec2[:, :]
#         prec_comb[perm[connections[0]], perm[connections[1]]] = 1
#         prec_comb[perm[connections[1]], perm[connections[0]]] = 1
#         print prec_comb, "combined",n, "n"
#     else:
    if extra == 1:
        n = n-1
    prec_comb = np.zeros((n,n))
    prec_comb[np.ix_(part1, part1)] = prec1[:, :]
#     print ind2, n, "index 2, n"
#     print prec2

    prec_comb[np.ix_(part2, part2)] = prec2[:, :]
    prec_comb[connections[0], connections[1]] = 1
    prec_comb[connections[1],connections[0]] = 1
#     prec_comb[perm[connections[0]], perm[connections[1]]] = 1
#     prec_comb[perm[connections[1]], perm[connections[0]]] = 1
#     if extra == 1:
#         comb_part = np.concatenate((part1, part2))
#         pos_temp1 = np.where(comb_part == n-1)
#         pos_temp2 = pos_temp1[0]
#         pos = pos_temp2[0]
# #         print pos
#         prec_comb = np.delete(prec_comb, pos, 0)
#         prec_comb = np.delete(prec_comb, pos, 1)
    print prec_comb, "combined",n, "n"
    return prec_comb
"""

In [ ]:
a = [0,1,2,3